apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: runs.pipeline.1eedaegon.github.io
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  labels:
  {{- include "pipeline-operator.labels" . | nindent 4 }}
spec:
  group: pipeline.1eedaegon.github.io
  names:
    kind: Run
    listKind: RunList
    plural: runs
    singular: run
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.runState
      name: RunState
      type: string
    - jsonPath: .status.currentJob
      name: CurrentJob
      type: string
    - jsonPath: .status.initializing
      name: Initializing
      type: integer
    - jsonPath: .status.waiting
      name: Waiting
      type: integer
    - jsonPath: .status.stopping
      name: Stopping
      type: integer
    - jsonPath: .status.running
      name: Running
      type: integer
    - jsonPath: .status.deleting
      name: Deleting
      type: integer
    - jsonPath: .status.completed
      name: Completed
      type: integer
    - jsonPath: .status.deleted
      name: Deleted
      type: integer
    - jsonPath: .status.failed
      name: Failed
      type: integer
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              env:
                additionalProperties:
                  type: string
                type: object
              historyLimit:
                properties:
                  amount:
                    type: integer
                  date:
                    type: string
                type: object
              inputs:
                items:
                  type: string
                type: array
              jobs:
                items:
                  properties:
                    args:
                      items:
                        type: string
                      type: array
                    command:
                      type: string
                    env:
                      additionalProperties:
                        type: string
                      type: object
                    image:
                      type: string
                    inputs:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                    namespace:
                      type: string
                    outputs:
                      items:
                        type: string
                      type: array
                    resource:
                      properties:
                        cpu:
                          type: string
                        gpu:
                          properties:
                            amount:
                              type: integer
                            type:
                              type: string
                          type: object
                        memory:
                          type: string
                      type: object
                    runBefore:
                      items:
                        type: string
                      type: array
                    schedule:
                      properties:
                        endDate:
                          type: string
                        scheduleDate:
                          type: string
                      type: object
                    trigger:
                      type: string
                  type: object
                type: array
              outputs:
                items:
                  type: string
                type: array
              resource:
                properties:
                  cpu:
                    type: string
                  gpu:
                    properties:
                      amount:
                        type: integer
                      type:
                        type: string
                    type: object
                  memory:
                    type: string
                type: object
              runBefore:
                items:
                  type: string
                type: array
              schedule:
                properties:
                  endDate:
                    type: string
                  scheduleDate:
                    type: string
                type: object
              trigger:
                type: boolean
              volumes:
                items:
                  properties:
                    capacity:
                      type: string
                    name:
                      type: string
                    storage:
                      type: string
                  type: object
                type: array
            type: object
          status:
            properties:
              JobStates:
                items:
                  properties:
                    jobState:
                      type: string
                    name:
                      type: string
                    reason:
                      type: string
                  type: object
                type: array
              completed:
                type: integer
              createDate:
                format: date-time
                type: string
              deleted:
                type: integer
              deleting:
                type: integer
              failed:
                type: integer
              initializing:
                type: integer
              lastUpdateDate:
                format: date-time
                type: string
              runState:
                type: string
              running:
                type: integer
              stopping:
                type: integer
              waiting:
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []