swagger: "2.0"
info:
  title: Kubernetes
  version: v1.30.0
paths:
$paths
definitions:
$definitions
securityDefinitions:
  BearerToken:
    description: Bearer Token authentication
    type: apiKey
    name: authorization
    in: header
security:
  - BearerToken: []
